/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * Roblox Studio AI - Chatbot API for Roblox game modification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * Returns the currently logged-in Roblox user, or null if not authenticated
 * @summary Get current authenticated user
 */
export declare const GetMeResponse: zod.ZodObject<{
    authenticated: zod.ZodBoolean;
    user: zod.ZodOptional<zod.ZodObject<{
        id: zod.ZodString;
        robloxId: zod.ZodString;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: string;
        robloxId: string;
        username: string;
        displayName: string;
        createdAt: string;
        avatarUrl?: string | null | undefined;
    }, {
        id: string;
        robloxId: string;
        username: string;
        displayName: string;
        createdAt: string;
        avatarUrl?: string | null | undefined;
    }>>;
}, "strip", zod.ZodTypeAny, {
    authenticated: boolean;
    user?: {
        id: string;
        robloxId: string;
        username: string;
        displayName: string;
        createdAt: string;
        avatarUrl?: string | null | undefined;
    } | undefined;
}, {
    authenticated: boolean;
    user?: {
        id: string;
        robloxId: string;
        username: string;
        displayName: string;
        createdAt: string;
        avatarUrl?: string | null | undefined;
    } | undefined;
}>;
/**
 * Clears the session and logs the user out
 * @summary Log out current user
 */
export declare const LogoutResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    success: boolean;
}, {
    success: boolean;
}>;
/**
 * Returns all chat sessions for the current user
 * @summary List chat sessions
 */
export declare const ListChatSessionsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    projectName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    messageCount: zod.ZodNumber;
    lastMessageAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
    createdAt: string;
    title: string;
    messageCount: number;
    projectName?: string | null | undefined;
    lastMessageAt?: string | null | undefined;
}, {
    id: string;
    createdAt: string;
    title: string;
    messageCount: number;
    projectName?: string | null | undefined;
    lastMessageAt?: string | null | undefined;
}>;
export declare const ListChatSessionsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    projectName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    messageCount: zod.ZodNumber;
    lastMessageAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
    createdAt: string;
    title: string;
    messageCount: number;
    projectName?: string | null | undefined;
    lastMessageAt?: string | null | undefined;
}, {
    id: string;
    createdAt: string;
    title: string;
    messageCount: number;
    projectName?: string | null | undefined;
    lastMessageAt?: string | null | undefined;
}>, "many">;
/**
 * Creates a new chat session for a Roblox project
 * @summary Create a new chat session
 */
export declare const CreateChatSessionBody: zod.ZodObject<{
    title: zod.ZodString;
    projectName: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    projectName?: string | undefined;
}, {
    title: string;
    projectName?: string | undefined;
}>;
export declare const CreateChatSessionResponse: zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    projectName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    messageCount: zod.ZodNumber;
    lastMessageAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
    createdAt: string;
    title: string;
    messageCount: number;
    projectName?: string | null | undefined;
    lastMessageAt?: string | null | undefined;
}, {
    id: string;
    createdAt: string;
    title: string;
    messageCount: number;
    projectName?: string | null | undefined;
    lastMessageAt?: string | null | undefined;
}>;
/**
 * @summary Get a specific chat session
 */
export declare const GetChatSessionParams: zod.ZodObject<{
    sessionId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
}, {
    sessionId: string;
}>;
export declare const GetChatSessionResponse: zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    projectName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    messageCount: zod.ZodNumber;
    lastMessageAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
    createdAt: string;
    title: string;
    messageCount: number;
    projectName?: string | null | undefined;
    lastMessageAt?: string | null | undefined;
}, {
    id: string;
    createdAt: string;
    title: string;
    messageCount: number;
    projectName?: string | null | undefined;
    lastMessageAt?: string | null | undefined;
}>;
/**
 * @summary Delete a chat session
 */
export declare const DeleteChatSessionParams: zod.ZodObject<{
    sessionId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
}, {
    sessionId: string;
}>;
export declare const DeleteChatSessionResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    success: boolean;
}, {
    success: boolean;
}>;
/**
 * @summary List messages in a session
 */
export declare const ListMessagesParams: zod.ZodObject<{
    sessionId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
}, {
    sessionId: string;
}>;
export declare const ListMessagesResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    sessionId: zod.ZodString;
    role: zod.ZodEnum<["user", "assistant"]>;
    content: zod.ZodString;
    codeSnippet: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    codeLanguage: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
    createdAt: string;
    sessionId: string;
    role: "user" | "assistant";
    content: string;
    codeSnippet?: string | null | undefined;
    codeLanguage?: string | null | undefined;
}, {
    id: string;
    createdAt: string;
    sessionId: string;
    role: "user" | "assistant";
    content: string;
    codeSnippet?: string | null | undefined;
    codeLanguage?: string | null | undefined;
}>;
export declare const ListMessagesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    sessionId: zod.ZodString;
    role: zod.ZodEnum<["user", "assistant"]>;
    content: zod.ZodString;
    codeSnippet: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    codeLanguage: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
    createdAt: string;
    sessionId: string;
    role: "user" | "assistant";
    content: string;
    codeSnippet?: string | null | undefined;
    codeLanguage?: string | null | undefined;
}, {
    id: string;
    createdAt: string;
    sessionId: string;
    role: "user" | "assistant";
    content: string;
    codeSnippet?: string | null | undefined;
    codeLanguage?: string | null | undefined;
}>, "many">;
/**
 * Sends a user message and returns the AI assistant response with optional Roblox script modifications
 * @summary Send a message and get AI response
 */
export declare const SendMessageParams: zod.ZodObject<{
    sessionId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    sessionId: string;
}, {
    sessionId: string;
}>;
export declare const SendMessageBody: zod.ZodObject<{
    content: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    content: string;
}, {
    content: string;
}>;
export declare const SendMessageResponse: zod.ZodObject<{
    id: zod.ZodString;
    sessionId: zod.ZodString;
    role: zod.ZodEnum<["user", "assistant"]>;
    content: zod.ZodString;
    codeSnippet: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    codeLanguage: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
    createdAt: string;
    sessionId: string;
    role: "user" | "assistant";
    content: string;
    codeSnippet?: string | null | undefined;
    codeLanguage?: string | null | undefined;
}, {
    id: string;
    createdAt: string;
    sessionId: string;
    role: "user" | "assistant";
    content: string;
    codeSnippet?: string | null | undefined;
    codeLanguage?: string | null | undefined;
}>;
/**
 * Returns summary stats - total sessions, messages, recent activity
 * @summary Get chat statistics summary
 */
export declare const GetChatStatsResponse: zod.ZodObject<{
    totalSessions: zod.ZodNumber;
    totalMessages: zod.ZodNumber;
    sessionsThisWeek: zod.ZodNumber;
    messagesThisWeek: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    totalSessions: number;
    totalMessages: number;
    sessionsThisWeek: number;
    messagesThisWeek: number;
}, {
    totalSessions: number;
    totalMessages: number;
    sessionsThisWeek: number;
    messagesThisWeek: number;
}>;
//# sourceMappingURL=api.d.ts.map